### ISSUE TITLE
how to import wallet account instead of creating account?

### ISSUE THREAD

**Issue by jayarajb1116** [argentlabs/web3.swift#111]

**Comment by jayarajb1116** [comment]
added below method to EthereumAccount class and worked.

public static func importAccount(keyStorage: EthereumKeyStorageProtocol, privateKey: String, keystorePassword password: String) throws -> EthereumAccount {
        guard let privateKey = privateKey.web3.hexData else {
            throw EthereumAccountError.createAccountError
        }
        
        do {
            let encodedData = try KeystoreUtil.encode(privateKey: privateKey, password: password)
            try keyStorage.storePrivateKey(key: encodedData)
            return try self.init(keyStorage: keyStorage, keystorePassword: password)
        } catch {
            throw EthereumAccountError.createAccountError
        }
    }

**Comment by DarthMike** [comment]
We don't have an explicit `import` method as the means of creating account is up to user of library. What you did above is correct.
