### ISSUE TITLE
Can't interact with the client methods

### ISSUE THREAD

**Issue by Gabets** [argentlabs/web3.swift#149]
Hi all!
When I try 
``` swift
guard let clientUrl = URL(string: "https://mainnet.infura.io/v3/<my infura id>") else { return }
let client = EthereumClient(url: clientUrl)
client.net_version(completion: { (error, network) in ...
// or
client.eth_gasPrice { (error, gasPrice) in
```
I got error:
Task <...>.<1> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://mainnet.infura.io/v3/b2f4b3f635d8425c96854c3d28ba6bb0, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://mainnet.infura.io/v3/b2f4b3f635d8425c96854c3d28ba6bb0}

Connection 1: unable to determine interface type without an established connection
Connection 1: unable to determine fallback status without a connection
Task <...>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])

and error description: The operation couldn’t be completed. (web3.EthereumClientError error 2.) 

also tried with the similar url for Kovan https://kovan.infura.io/v3/<my infura id>
also used urls from tests
https://ropsten.infura.io/v3/b2f4b3f635d8425c96854c3d28ba6bb0"
https://mainnet.infura.io/v3/b2f4b3f635d8425c96854c3d28ba6bb0

what am i doing wrong?

**Comment by DarthMike** [comment]
Hello @Gabets, are you using a playground or script for testing? You need to keep the `client` in memory by locking the thread (DIspatchSemaphore for example), maybe it's cancelled because `client` is deallocated?

**Comment by Gabets** [comment]
Hello @DarthMike 
I created a simple app and run this code inside my view controller after pressing the button
```swift
DispatchQueue.global().async {
    self.testing()
} 
```

**Comment by Gabets** [comment]
@DarthMike 
I'm sorry for my stupid question, but when I create client as global variable, everything worked fine

Maybe in the future I will have more questions, but this issue can be closed.
