### ISSUE TITLE
ERC721Metadata.tokenURI call returns no data. Expected to return json metadata.

### ISSUE THREAD

**Issue by bejitono** [argentlabs/web3.swift#152]
I'm trying to get the token URI with the below code but don't receive any response data.

```
let erc721 = ERC721Metadata(
    client: client,
    metadataSession: .shared
)
erc721.tokenURI(
    contract: EthereumAddress("0x3b3ee1931dc30c1957379fac9aba94d1c48a5405"),
    tokenID: BigUInt(37949)
) { error, url in
    if let error = error { return print(error) }
    print(url)
}
```

Using the same input with Boilertalk's Web3.swift framework I receive the following response: 

`["": "https://ipfs.foundation.app/ipfs/QmWiWTXdRCbiCm6n1BEujGJMA8GJNpmGx88nbmf5QcdYzA/metadata.json"]`

Thanks a lot for your work guys!

**Comment by DarthMike** [comment]
Hello @bejitono I can't read any `tokenURI` (token ID 0 or 37949) using [etherescan](https://etherscan.io/address/0x3b3ee1931dc30c1957379fac9aba94d1c48a5405#readProxyContract). The behaviour seems correct in this case.
