### ISSUE TITLE
Getting started SwiftUI with EthereumClient

### ISSUE THREAD

**Issue by wilks7** [argentlabs/web3.swift#154]
I am having an issue getting started, It looks like the issue is with the EthereumClient and strong reference but I can't seem to figure it out, I keep getting errors, is this not the correct method using SwiftUI ?

        class ContractManager {
        
            let client: EthereumClient!
            let account: EthereumAccount!
        
            init() {
                let keyStorage = EthereumKeyLocalStorage()
                account = try! EthereumAccount.create(keyStorage: keyStorage, keystorePassword: "MY_PASSWORD")
                client = EthereumClient(url: URL(string: "https://mainnet.infura.io/v3/238a6eb832834984ae827fc59dd1d992")!)
            }
        
            func getGasPrice() {
                client.eth_gasPrice { (error, currentPrice) in
                    guard error != nil else {
                        print(error?.localizedDescription)
                        return
                    }
                    print("The current gas price is \(currentPrice)")
                }
            }
            
        }
        
        struct ContentView: View {
            
            let contractManager = ContractManager()
            
            var body: some View {
                VStack(alignment: .leading, spacing: 10) {
                    
                    Button("Get Gas"){
                        contractManager.getGasPrice()
                    }
                }
            }
        }

**Comment by DarthMike** [comment]
Hello, `SwiftUI` works differently, your `contractManager` property is discarded right after the view is rendered by the system, you'll need to use [@ObservedObject](https://developer.apple.com/documentation/swiftui/managing-model-data-in-your-app)
