### ISSUE TITLE
Cannot find 'EthereumJSONContract' in scope

### ISSUE THREAD

**Issue by JulienLevallois** [argentlabs/web3.swift#160]
Hey, I have this error. Do you know what's the problem?
From this article
https://www.argent.xyz/blog/building-ethereum-dapps-on-ios-with-web3-swift/

Thanks
<img width="1342" alt="Capture d’écran 2021-11-29 à 12 21 08" src="https://user-images.githubusercontent.com/5727223/143913924-be3b6d82-f9d6-4e5f-a62b-75112cc31dc2.png">
r

**Comment by DarthMike** [comment]
We removed support for JSON contracts to simplify the library and because the statically typed support is a better alternative.
