### ISSUE TITLE
Mismatch podspec in master branch and the version published in cocoapods

### ISSUE THREAD

**Issue by michaellee8** [argentlabs/web3.swift#163]
In #161 , I applied a fix of broken build when not using frameworks in the podspec. However, it seems that it was not published to cocopods, as in https://github.com/CocoaPods/Specs/blob/master/Specs/a/9/6/web3.swift/0.8.1/web3.swift.podspec.json and https://github.com/argentlabs/web3.swift/blob/master/web3.swift.podspec. Please have a look at this.

**Comment by DarthMike** [comment]
@michaellee8 just published 0.8.2 with the change
