### ISSUE TITLE
Linux transactions fail

### ISSUE THREAD

**Issue by dnKaratzas** [argentlabs/web3.swift#175]
On Linux I get when I try to transfer tokens.
"Ethereum response error: JSONRPCErrorDetail(code: -32000, message: "insufficient funds for gas * price + value")"

On macOS that error does not occur and the transaction completes successfully. Checked BSScan and the Gas, Limit etc are all ok. Any idea what might me wrong?

**Comment by DarthMike** [comment]
@dnKaratzas I have no idea how Linux would be different unless `BigInt` library has a bug encoding the value in the platform. We don't use Linux ourselves (and CI only tests iOS), maybe @rkreutz has encountered this?

**Comment by dnKaratzas** [comment]
Btw my TestNet Account balance: 1.3202
I printed the txArray to debug and seems ok:

txArray: [Optional(151), Optional(5000000000), Optional(1000000), Optional("9ac64cc6e4415144c455bd8e4837fea55603e5c3"), Optional(100000000000000000), Optional(228 bytes), Optional(229), Optional(32 bytes), Optional(32 bytes)]

I dont know how to debug it under Linux :(

**Comment by rkreutz** [comment]
TBH I hadn't tested executing an actual transaction, but if it's complaining about insufficient gas is most likely an encoding issue on the transaction... maybe share the code you are trying to run so others can take a look as well?

**Comment by dnKaratzas** [comment]
I swap token on pancakeSwap by calling swapExactTokensForETHSupportingFeeOnTransferTokens method

`public struct swapExactTokensForETHSupportingFeeOnTransferTokens: ABIFunction {
		public static let name = "swapExactTokensForETHSupportingFeeOnTransferTokens"
		public let gasPrice: BigUInt?
		public let gasLimit: BigUInt?
		public var contract: EthereumAddress
		public let from: EthereumAddress?
		public let value: BigUInt

		public let amountOutMin: BigUInt
		public let path: [EthereumAddress]
		public let to: EthereumAddress
		public let deadline: BigUInt

		public init(contract: EthereumAddress,
					from: EthereumAddress? = nil,
					gasPrice: BigUInt? = nil,
					gasLimit: BigUInt? = nil,
					value: BigUInt,
					amountOutMin: BigUInt,
					path: [EthereumAddress],
					to: EthereumAddress,
					deadline: BigUInt) {
			self.contract = contract
			self.from = from
			self.gasPrice = gasPrice
			self.gasLimit = gasLimit
			self.value = value

			self.amountOutMin = amountOutMin
			self.path = path
			self.to = to
			self.deadline = deadline
		}

		public func encode(to encoder: ABIFunctionEncoder) throws {
			try encoder.encode(value)
			try encoder.encode(amountOutMin)
			try encoder.encode(path)
			try encoder.encode(to)
			try encoder.encode(deadline)
		}
	}`

`let function = Web3Functions.swapExactTokensForETHSupportingFeeOnTransferTokens(contract: pancakeSwapRouterAddress,
																							from: wallet.address,
																							gasPrice: gasPrice,
																							gasLimit: gasLimit,
																							value: amount,
																							amountOutMin: BigUInt(0),
																							path: [tokenAddress, liquidityPairAddress],
																							to: wallet.address,
																							deadline: time)
			let transaction = try function.transaction()

			let txHash = try await withCheckedThrowingContinuation({ (continuation: CheckedContinuation<String, Error>) in
				web3Client.eth_sendRawTransaction(transaction, withAccount: wallet) { error, txHash in
					if let error = error {
						continuation.resume(throwing: error)
						return
					}

					guard let txHash = txHash else {
						continuation.resume(throwing: "buy: txHash is nil")
						return
					}
					continuation.resume(returning: txHash)
				}
			})`

**Comment by DarthMike** [comment]
@dnKaratzas where can we find the solidity code or JSON ABI for `swapExactTokensForETHSupportingFeeOnTransferTokens` ?

**Comment by dnKaratzas** [comment]
Here is the PancakeSwap router address on testnet 
https://testnet.bscscan.com/address/0x9Ac64Cc6e4415144C455BD8E4837Fea55603e5c3#writeContract

**Comment by DarthMike** [comment]
I don't see anything wrong with the function declaration. Maybe it's worth comparing the `transaction.data` and see if values are correctly encoded.

**Comment by dnKaratzas** [comment]
I already did that and seems ok. I really dont get it what is wrong with linux

**Comment by dnKaratzas** [comment]
@DarthMike  & @rkreutz  do you have any Linux machine to debug that?

**Comment by rkreutz** [comment]
not really, I'd have to run it on a docker image, which is not really ideal for debugging anyway, could you maybe try printing both `transaction.data` and see if there is a difference there?

**Comment by dnKaratzas** [comment]
@rkreutz ok

**Comment by dnKaratzas** [comment]
@rkreutz  how can I print the data as a string? Do we have any func for that?

**Comment by dnKaratzas** [comment]
@rkreutz here you are 

@rkreutz 

macOS:

```bash
from: xxx
to: 0x9ac64cc6e4415144c455bd8e4837fea55603e5c3
data: 228 bytes
dataHexStr: Optional("0xb6f9de9500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a1a8c403357ed872ea66884fd2ad67d7868cc9910000000000000000000000000000000000000000055037e147306fce43a390000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000ae13d989dac2f0debff460ac112a837c89baa7cd000000000000000000000000dacbdecc2992a63390d108e8507b98c7e2b5584a")
nonce: nil
gasPrice: Optional(5000000000)
gasLimit: Optional(1000000)
chainId: nil
gas: nil
blockNumber: nil
hash: nil
```
Linux
```bash
from: xxx
to: 0x9ac64cc6e4415144c455bd8e4837fea55603e5c3
data: 228 bytes
dataHexStr: Optional("0xb6f9de9500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a1a8c403357ed872ea66884fd2ad67d7868cc9910000000000000000000000000000000000000000055037f976332e4f422108000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000ae13d989dac2f0debff460ac112a837c89baa7cd000000000000000000000000dacbdecc2992a63390d108e8507b98c7e2b5584a")
nonce: nil
gasPrice: Optional(5000000000)
gasLimit: Optional(1000000)
chainId: nil
gas: nil
blockNumber: nil
hash: nil
```

**Comment by rkreutz** [comment]
I've noticed the data hex on both don't exactly match, is that the deadline param or something else? If it is something else, maybe that's the issue?

**Comment by dnKaratzas** [comment]
> I've noticed the data hex on both don't exactly match, is that the deadline param or something else? If it is something else, maybe that's the issue?

@rkreutz  Yes its the deadline. I removed that and now are identical. Updated the results above

**Comment by rkreutz** [comment]
then I'm out of ideas 😂 maybe try something simple first, just try sending some BNB to another wallet, see if that goes through, then try a simple BEP-20 transfer?

**Comment by dnKaratzas** [comment]
@rkreutz tried and have the same error. I start to believe that is signing issue! When you sign the params...

**Comment by rkreutz** [comment]
The RPC says is a gas issue though, don't think it would be related to signing... you could use ethers-js to check if the signature is correct if that's the case

**Comment by rkreutz** [comment]
Can you try moving some ETH around on ropstein or kovan? Could it be an issue with BSc test net?

**Comment by dnKaratzas** [comment]
I tried also on mainnet same thing... The signatures are different on mac and linux dont know if they suppose to be the same. How can I use ether-js?

**Comment by dnKaratzas** [comment]
Do you have discord or something for better communication?

**Comment by rkreutz** [comment]
I do have a discord account, though I'm probably not the best person to go through it with you since the most involvement I had with this project was opening that PR that is linked in the comments, I don't have prior knowledge of this library and I'm not a member of the team maintaining the project, just someone who wanted to help :)

If you want to chat just send over your Discord account, I'll add you there and we can talk more once I'm finished with business hours. Cheers

**Comment by DarthMike** [comment]
@dnKaratzas Yes it doesn't seem to be an encoding issue; you're definitely connecting to the same node from your mac and in the Linux machine? I'm a bit lost with BSC though; no idea how it works.

**Comment by dnKaratzas** [comment]
@DarthMike  I believe it has to do with the sign of the transaction....

**Comment by rkreutz** [comment]
@dnKaratzas you can use the following typescript code to check the signature, steps are:
- run `npm install`
- edit `main.ts` to add the `txDigest` (the Keccak hash of the whole transaction) and the `signature`; I'm not too sure how to get those from Web3.swift though, you'd need to investigate that
- then run with `npm run main`

It should print on your terminal the address that made that signature, if the address matches with your address then the signature is good.
[ethers-playground.zip](https://github.com/argentlabs/web3.swift/files/8042258/ethers-playground.zip)

**Comment by rkreutz** [comment]
Definitely looks like a signing issue, it could be also an issue with whatever framework/code is being used to import the private key, maybe on Linux that is generating a different signing address?

**Comment by dnKaratzas** [comment]
If you want add me to discord Dio89#4424

**Comment by dnKaratzas** [comment]
As @rkreutz  mentioned I have tested the fix under Linux and is working perfectly!
Congrats :)

**Comment by DarthMike** [comment]
@rkreutz Thanks for looking into this. All PRs should be against `develop`. `master` is what's released, we'll merge after next release with all changes.

**Comment by DarthMike** [comment]
Mid-longer term we can set up CI to run tests in Linux given we've seen some things might be different. Will require some work as we currently only build iOS with Bitrise.

**Comment by rkreutz** [comment]
@DarthMike @dnKaratzas FYI PR is up
