### ISSUE TITLE
Multiple targets named "CryptoSwift" when using web3.swift

### ISSUE THREAD

**Issue by simonmcl** [argentlabs/web3.swift#176]
I'm using a dependency in my app that imports CryptoSwift and web3.swift. You recently made a change to use an embedded version of CryptoSwift:

```
.target(name: "CryptoSwift",
                dependencies: [],
                path: "web3swift/lib/CryptoSwift"),
```

and named the target the same as the official package version. Now any package or app that tries to import CryptoSwift and web3.swift is getting build failures "multiple targets named `CryptoSwift` in: `cryptoswift`, `web3.swift`". Because it was only a minor version bump too, its being automatically pulled down.

Can you either rename your target, or ideally use the official CryptoSwift as a listed dependency so there won't be 2 copies of the same code

**Comment by DarthMike** [comment]
Hey @simonmcl yes we will change the local dependency name. Don't want to force a new dependency though. You can still use the previous release until it's fixed (`0.8.2`)

**Comment by simonmcl** [comment]
@DarthMike thanks. Yes i've asked the dependency i'm using to make that change for now, but it will take time for that. Is there a reason you need a local copy and can't use the official version? having 2 copies of CryptoSwift in my app is not ideal

**Comment by DarthMike** [comment]
@simonmcl we don't use a full copy of `CryptoSwift`, just needed `PDFK2` implementation. See #167

**Comment by simonmcl** [comment]
@DarthMike ah ok, its only a piece ok then yeah makes sense to just rename it. Thanks

**Comment by DarthMike** [comment]
`0.9.1` should fix this
