### ISSUE TITLE
How do you export a private key that's password protected

### ISSUE THREAD

**Issue by daltonclaybrook** [argentlabs/web3.swift#181]
If a private key is password-protected, `EthereumAccount` encrypts the key before passing it to key storage, which makes sense. But I can't find a way to access the decrypted private key data from app so that I can export it. The `privateKeyData` property on `EthereumAccount` is private, and the `KeystoreUtil` class is internal, so I can't just use it to decode the key manually. Is there another way? Do you see any problem with exposing a public accessor for the private key?

**Comment by DarthMike** [comment]
I don't see any problem, just need a public method accepting a `String` password to decrypt, returning raw key `Data`

**Comment by daltonclaybrook** [comment]
Would you add the method to `EthereumKeyStorageProtocol`, or update `EthereumAccount` to expose the `privateKeyData` field?

**Comment by DarthMike** [comment]
I think encrypt/decrypt can be moved to `EthereumKeyStorageProtocol` as an extension to the protocol.
Any type implementing storage only needs the existing methods:
```swift
func storePrivateKey(key: Data) throws -> Void
func loadPrivateKey() throws -> Data
```

And a protocol extension can add store/load with the encrypt/decrypt step (currently implemented in `EthereumAccount`).
