### ISSUE TITLE
The latest version not yet available on Cocoapods

### ISSUE THREAD

**Issue by Mattijah** [argentlabs/web3.swift#186]
It looks like the latest version (`0.9.3`) is not yet available on Cocoapods. The last version seems to be `0.8.2` on there.

**Comment by DarthMike** [comment]
Yes we're aware; there's an issue validating with `pod trunk`. You can use the `master` branch in the meantime.

**Comment by Mattijah** [comment]
Hey @DarthMike, thanks for your reply. I've actually had the same problem with validating pods for my own libraries as their backend was down (is this the issue you're talking about?). If so, did you try running `pod trunk me`? It helped in my case and I was able to push the trunk.

**Comment by DarthMike** [comment]
Latest version is now available through Cocapods @Mattijah
