### ISSUE TITLE
Can I call a custum smart contract function using this library?

### ISSUE THREAD

**Issue by yuchenz27** [argentlabs/web3.swift#199]
I have a custom smart contract deployed on the Ethereum blockchain and I want to interact with it using Swift (sending transactions and viewing state). 

Is this library capable of sending custom transaction? Thank you very much.

**Comment by DarthMike** [comment]
Yes, see example in [README](https://github.com/argentlabs/web3.swift#smart-contracts-static-types)
You'll need to use [ABIFunction](https://github.com/argentlabs/web3.swift/blob/master/web3swift/src/Contract/Statically%20Typed/ABIFunction.swift) with your ABI statically defined using Swift types.
