### ISSUE TITLE
Cannot add package

### ISSUE THREAD

**Issue by daihovey** [argentlabs/web3.swift#209]
I am not able to add the package, is this something on your end, mine, or Apples?
<img width="663" alt="Screen Shot 2022-05-18 at 7 02 13 pm" src="https://user-images.githubusercontent.com/47039937/169001799-24894b3e-ab4e-4dc8-9976-bb87cb2a67c6.png">

**Comment by DarthMike** [comment]
@daihovey Didn't see this issue before, but based on the error, it looks like Apple repository?
What version are you trying to add?

**Comment by daihovey** [comment]
Weird, `0.9.3` used to work. Nothing works now. A friend got it working so i must be something locally for me, fun.

**Comment by dnKaratzas** [comment]
Clean derived data and you will be fine!

**Comment by daihovey** [comment]
It was something to do with package caches.
I fixed it removing all the caches, finding the web3 package, you can “Add it anyway” and then do the turn off everything dance and the hit Reset Package Caches.
