### ISSUE TITLE
Fetching ENS TextRecords

### ISSUE THREAD

**Issue by Tomas-Shao** [argentlabs/web3.swift#245]
Hi, i am fetching the ENS TextRecords by using this:

```
    func fetchTextRecords(node: String, key: String) async throws -> String {
        let client = EthereumClient(url: URL(string: EthereumNetwork.Rinkeby.rpcUrl!)!)
        let contractAddress = EthereumAddress("0xf6305c19e814d2a75429Fd637d01F7ee0E77d615")

        let function = TextRecord(contract: contractAddress, node: node.namehash.web3.hexData ?? Data(), key: key)
        let transaction = try function.transaction()
        return try await client.eth_call(transaction)
    }
```

But the return value is 
```
0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002c485a506857354e4171713864376e73675a5567716a4374375a66534a7871454c717132356a6a313468784d310000000000000000000000000000000000000000
```

I decoded the above value by using `.web3.stringValue`, But got a 

������������������������������� �������������������������������,HZPhW5NAqq8d7nsgZUgqjCt7ZfSJxqELqq25jj14hxM1��������������������

The expected value should be : `HZPhW5NAqq8d7nsgZUgqjCt7ZfSJxqELqq25jj14hxM1`

so my questions is:

1. Why get such a result (with so many zeros).
2. How to decode this if this is by design?

BTW: I used "web3": "^1.7.3" in react-native, it works well :
<img width="447" alt="image" src="https://user-images.githubusercontent.com/66241503/174466760-f979fe22-c804-4130-8170-76d5abdc5655.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/66241503/174466787-e351172b-d78b-4b0b-be96-d2c2a008ba97.png">

**Comment by DarthMike** [comment]
Hello @Tomas-Shao can you show the code for `TextRecord`, specifically, the response decoding?

**Comment by DarthMike** [comment]
Hello @Tomas-Shao that response is the raw bytes, and the library will help decoding into a Swift String. 

It's simpler to use `ABIFunction.call` which will help decoding by forcing to provide a decodable type conforming to `ABIResponse`:
See [here](https://github.com/argentlabs/web3.swift/blob/develop/web3swift/src/Contract/Statically%20Typed/EthereumClient%2BStatic.swift#L18-L23)

I suspect you just need to decode from String, can reuse `StringResponse` from `ENSContracts`

**Comment by Tomas-Shao** [comment]
Thanks @DarthMike , it works!!
```
let function = TextRecord(contract: contractAddress, node: node.namehash.web3.hexData ?? Data(), key: key)
return try await function.call(withClient: client, responseType: ENSContracts.StringResponse.self).value
```
