### ISSUE TITLE
EthereumAccount - runtime decoding of ABI in JSON format.

### ISSUE THREAD

**Issue by JeneaVranceanu** [argentlabs/web3.swift#250]
Hello! 
I was looking for a possibility to decode smart contract ABI and it looks like `EthereumAccount` is a centrepiece where such a feature could be located. It appears that ABI should be statically defined, is that correct? 
Wondering if I missed this feature somewhere.

Here is an example of random ABI:
```
[
	{
		"inputs": [],
		"name": "increment",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	}
]
```

**Comment by DarthMike** [comment]
We dropped parsing String-typed ABI from the library as it's not safe and bloats the codebase. It's better to know the ABI the application/tool is interacting with beforehand.
