### ISSUE TITLE
ABI Code gen

### ISSUE THREAD

**Issue by ismail9001** [argentlabs/web3.swift#253]
Can we implement some ABI structs generator? 

It would be very convenient to convert ABI.json to ABIFunction type entities

**Comment by DarthMike** [comment]
We have a very dumb codegen for Argent, never fully implemented anything generic. Always wanted but never had time.

**Comment by imanrep** [comment]
so until now, there is no ABI generator from json to ABIFunctions

**Comment by imanrep** [comment]
hi @DarthMike i wrote code using nodejs to create ContractABI from JSON to swift file. please take a look :)
<a href="https://github.com/imanrep/swiftabigen">swiftabigen</a>
hope it helps

**Comment by DarthMike** [comment]
Added to README
