### ISSUE TITLE
EthereumNameService: resolve(address:) and resolve(addresses:)

### ISSUE THREAD

**Issue by Tomas-Shao** [argentlabs/web3.swift#259]
These two methods are a bit confusing to me, why do I not get the same result?
and what is the difference between these two methods?  
From the method names, I thought one was multiple calls together and the other could only call one at a time
do we have a api doc to say that?

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/66241503/181393447-f40e3cb2-7cb8-4c30-bc09-931021065077.png">
Thanks

**Comment by DarthMike** [comment]
Both should return the same result, one is to resolve multiple addresses with one call (using multicall), the other is to resolve a single address

**Comment by DarthMike** [comment]
I can't see any result in etherescan though, strange
https://etherscan.io/enslookup-search?search=0x2259c79c85141a59b9117c789a5ae09774b7572f

**Comment by Tomas-Shao** [comment]
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/66241503/188414620-4b64e6f6-2c69-4f55-8cd8-ad3db9002c01.png">
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/66241503/188415551-ebfb432a-739e-40c5-959d-f863ed044c8d.png">

Hi @DarthMike , thanks for you replying. you can check the UT:

```
import XCTest
import web3

class ENSContractTests: XCTestCase {

    var client: EthereumClient?

    override func setUpWithError() throws {
        // Put setup code here. This method is called before the invocation of each test method in the class.
        self.client = EthereumClient(url: URL(string: "https://rinkeby.infura.io/v3/84ae00fec54f4d65bd1c0505b0e96383")!)
    }

    func testMultipleResolve() async {
        let nameService = EthereumNameService(client: client!, registryAddress: EthereumAddress("0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"))

        var results: [EthereumNameService.ResolveOutput<String>]?

        let result = await nameService.resolve(addresses: [
            EthereumAddress("0x2259C79c85141A59b9117C789A5ae09774b7572f"),
        ])

        switch result {
        case .success(let resolutions):
            results = resolutions.map { $0.output }
        case .failure:
            break
        }

        XCTAssertEqual(results, [.resolved("zeliang.beagle.eth")])
    }

    func testResolve() async {
        let nameService = EthereumNameService(client: client!, registryAddress: EthereumAddress("0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"))

        let result = try? await nameService.resolve(address: EthereumAddress("0x2259C79c85141A59b9117C789A5ae09774b7572f"), mode: .onchain)

        XCTAssertEqual(result, "zeliang.beagle.eth")
    }
}
```

**Comment by DarthMike** [comment]
@Tomas-Shao I've added some tests in Goerli with the set up you reported, and I see no issues. Can you confirm it works for you now? See #284

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @Tomas-Shao)
