### ISSUE TITLE
Cannot inherit from non-open class 'ERC165' outside of its defining module

### ISSUE THREAD

**Issue by ParhamHatan** [argentlabs/web3.swift#262]
I want to inherit ERC165 for creating ERC1155 class but got this error in my app.

``` swift
public class ERC1155: ERC165 {} // <- Error line
```

**Comment by dnKaratzas** [comment]
I don't see a reason to get an error by inherit `ERC165`. Could you please share the error you get?

**Comment by ParhamHatan** [comment]
It restricted from inheriting because of ```public``` tag.
Error I got: ```Cannot inherit from non-open class 'ERC165' outside of its defining module```

**Comment by dnKaratzas** [comment]
I thought you wanted to edit the package. @DarthMike should we make the classes open for inheritance?

**Comment by DarthMike** [comment]
@dnKaratzas happy to make open, no problem

**Comment by DarthMike** [comment]
Fixed in #265
