### ISSUE TITLE
Ambiguous use of 'create(keyStorage:keystorePassword:)'

### ISSUE THREAD

**Issue by ParhamHatan** [argentlabs/web3.swift#263]
I want to create new ethereum account but got this error message
Error message: Ambiguous use of 'create(keyStorage:keystorePassword:)'

``` swift
let keyStorage = EthereumKeyLocalStorage()
let account = EthereumAccount.create(keyStorage: keyStorage, keystorePassword: "1234") // <- Error line
```

**Comment by DarthMike** [comment]
Hi you can use `1.2.0` while we fix the issue in `develop`

**Comment by aburashima** [comment]
Creating account with EthereumAccount.create(...) generates public key of 64 bytes size and private key of 425 bytes size.
Meanwhile, creating Ethereium account with Geth produces the keys of 20 and 32 bytes respectively.
Are the longer versions of the keys valid as well as the shorter ones?
