### ISSUE TITLE
EthereumNameService resolve failure

### ISSUE THREAD

**Issue by soulbind** [argentlabs/web3.swift#264]
EthereumNameService cannot reolve address to ens name.
Always repor 'ensUknown' while address bind a name.

**Comment by DarthMike** [comment]
Hello @soulbind can you provide an address in mainnet/ropsten to test it?

**Comment by Tomas-Shao** [comment]
same #259 ? i think yes,  
try 
```
nameService.resolve(addresses: [...])
```

**Comment by DarthMike** [comment]
Cool, we'll keep track with #259
