### ISSUE TITLE
iOS versions discrepancy

### ISSUE THREAD

**Issue by aburashima** [argentlabs/web3.swift#267]
The package is not compiled with error "Compiling for iOS 13.0, but module 'Internal_CryptoSwift_PBDKF2' has a minimum deployment target of iOS 14.0"
Attempt to upgrade the supported platform to iOS 14.0: iOS(SupportedPlatform.IOSVersion.v14) results in
errors in HttpNetworkProvider.swift "Concurrency is only available in iOS 15.0.0 or newer" 
How should this discrepancy be resolved?

**Comment by dnKaratzas** [comment]
What is your Xcode version? async/await is available for iOS 15, macOS Monterey, watchOS 8, and tvOS 15. Xcode 13.2 extends supported systems way back to iOS 13, macOS Catalina, watchOS 6, and tvOS 13.

**Comment by aburashima** [comment]
My Xcode version is 13.1.
Thus, I have to upgrade to 13.2 to eliminate the issue, haven't I?

**Comment by dnKaratzas** [comment]
Yeah!
