### ISSUE TITLE
Public key is much longer than that created with other means

### ISSUE THREAD

**Issue by aburashima** [argentlabs/web3.swift#272]
Creating account with EthereumAccount.create(...) generates private key of 425 bytes size.
Meanwhile, creating Ethereium account with other means (e.g., Geth) produces private key of 32 bytes long.
Is the longer version of the private key valid as well as the shorter one?

**Comment by DarthMike** [comment]
@aburashima What do you mean? As you can see in the unit tests, the key length is 32 bytes. I'm not sure I understand
https://github.com/argentlabs/web3.swift/blob/develop/web3swift/src/Account/EthereumAccount.swift#L88-L114
https://github.com/argentlabs/web3.swift/blob/develop/web3sTests/Utils/KeyUtilTests.swift#L19-L23

**Comment by aburashima** [comment]
> @aburashima What do you mean? As you can see in the unit tests, the key length is 32 bytes. I'm not sure I understand https://github.com/argentlabs/web3.swift/blob/develop/web3swift/src/Account/EthereumAccount.swift#L88-L114 https://github.com/argentlabs/web3.swift/blob/develop/web3sTests/Utils/KeyUtilTests.swift#L19-L23

Thank you for the reply!
I looked into the code more thoroughly and revealed that I had fetched the private key with method loadPrivateKey() instead of loadAndDecryptPrivateKey(keystorePassword:). 
Indeed, the latter returns 32 bytes long decrypted private key I need.
Everything is fine, please close the topic.

**Comment by DarthMike** [comment]
👍
