### ISSUE TITLE
WebSocketClient - NIOTSConnectionBootstrap not building in watchOS 9.0

### ISSUE THREAD

**Issue by warcupcake** [argentlabs/web3.swift#280]
Been trying to develop something on watchOS with this package and got the issue of that the WebSocketClient.swift file failed at building. The XCode issues says:

Occuring on both watchOS 9.0 and 9.1

![Screenshot 2565-11-21 at 22 15 34](https://user-images.githubusercontent.com/97900684/203090602-4d0ae496-0878-494f-bda0-9630e9ba1238.png)

**Comment by DarthMike** [comment]
@warcupcake Can you try if this branch works for you #287? I think it's related to package not supporting watchOS explicitly

**Comment by warcupcake** [comment]
@DarthMike Recently tried again with the new builds. The web3swift package says it supports watchOS but the websocket-kit doesn't. And the error is coming from that package. Is this package part of this library?
<img width="1343" alt="Screenshot 2566-01-06 at 10 57 11" src="https://user-images.githubusercontent.com/97900684/210927112-acb0b7f1-6468-4b99-a830-dafb2dceeb24.png">
