### ISSUE TITLE
EthereumNameService resolve(address:mode:) fails because resolver contract address is NOT ERC165 compliant

### ISSUE THREAD

**Issue by realimaginaryverse** [argentlabs/web3.swift#297]
Calling EthereumNameService resolve(address:mode:) throw an exception because supportsWildcard() is failing since the resolver does not implement supportsInterface method.

EthereumNameService resolve(name:supportingWildcard:) works because its resolver is different which is ERC165 compliant

**Comment by DarthMike** [comment]
Hi @realimaginaryverse not sure I understand correctly. Are you using your own resolver contract?
