### ISSUE TITLE
ABI Generator

### ISSUE THREAD

**Issue by imanrep** [argentlabs/web3.swift#305]
If you guys need ABI Generator for swift file using this dependencies, you can try here
https://github.com/imanrep/swiftabigen

![image](https://user-images.githubusercontent.com/86184667/214631561-612082d3-9fa3-4a30-850f-8bd87ece0ffb.png)

it will generate JSON file to Swift File and use the function directly.

Hope it helps the community
cheers ✌️

**Comment by DarthMike** [comment]
Great we'll add it to the README
