### ISSUE TITLE
It seems that getLogs can't get all the transaction logs, is there any other way? Please give me some help, thank you!

### ISSUE THREAD

**Issue by dengbangquan** [argentlabs/web3.swift#324]
It seems that getLogs can't get all the transaction logs, is there any other way? Please give me some help, thank you!

**Comment by dengbangquan** [comment]
@DarthMike hello！We are developing a new wallet that supports EVM. I want to get all transaction logs generated by transactions through web3.swift, but I haven't found a specific way.

**Comment by DarthMike** [comment]
The function `getLogs` from `EthereumClient` doesn't work for you?
