### ISSUE TITLE
Inconsistent dependencies for Secp256k1.swift between swift package manager and cocoapods

### ISSUE THREAD

**Issue by metalurgical** [argentlabs/web3.swift#341]
The dependencies between the SPM and Cocoapods are inconsistent.

Secp256k1.swift for SPM uses the GigaBitcoin repository:
```
.package(url: "https://github.com/GigaBitcoin/secp256k1.swift.git", .upToNextMajor(from: "0.6.0")),
```

Secp256k1.swift for CocoaPods uses the BoilerTalk repository:
```
s.dependency 'secp256k1.swift', '~> 0.1'
```
https://cocoapods.org/pods/secp256k1.swift

These need to be reconciled.

**Comment by DarthMike** [comment]
Unfortunately not all libraries offer Cocoapods. Specifically `GigaBitcoin` doesn't. We'll need to leave this as-is, and will remove Cocoapods support soon. Added a warning to README #348
