### ISSUE TITLE
Security Enhancement. 

### ISSUE THREAD

**Issue by bobgodwinx** [argentlabs/web3.swift#346]
I saw this line of [code](https://github.com/argentlabs/web3.swift/blob/master/web3swift/src/Account/EthereumKeyStorage.swift#L104) and I was wondering should we not encrypt the key before storing it ? 

NSKeyedArchiver.archiveRootObject is for storing setting etc .. it's not secure. I would suggest using the keychain or a symmetric key derivation via the user password to store the privateKeys.

**Comment by DarthMike** [comment]
`EthereumKeyLocalStorage` is not supposed to be used as-is, it's only an example. Maybe it's not clear in the codebase, and possibly be removed.
