### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by bitcoinbrisbane** [argentlabs/web3.swift#55]
Im getting 18 Swift compiler issues after adding the pod and opening my workspace.

- Redefinition of module 'CommonCrypto'
- Could not build module 'Dispatch'

etc

**Comment by einsteinx2** [comment]
Ran into the same issue. Removing the `frameworks` folder with the CommonCrypto module maps seems to resolve it.

**Comment by einsteinx2** [comment]
I think it was needed for earlier versions of Xcode/Swift but in the latest version CommonCrypto has a module map in Apple's SDK so it's now causing module redefinition errors.

**Comment by einsteinx2** [comment]
I've opened a PR here with the fix: https://github.com/argentlabs/web3.swift/pull/56

**Comment by DarthMike** [comment]
Thanks for contributing! 
Looks good, I'll check the PR in short, I just want to make sure it won't break our Argent builds. (Might need to update on our side as well)

**Comment by th3m477** [comment]
Please see the latest version available on `master`. Your issues should be resolved now 👍
