### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by daihovey** [argentlabs/web3.swift#67]
Hey,

in `EthereumAccountTests`

```
func testCreateAccount() {
        let account = try? EthereumAccount.create(keyStorage: EthereumKeyLocalStorage(), keystorePassword: "PASSWORD")
        XCTAssertNotNil(account)
    }
```
`account` is returning `nil`, and so failing.

Also, when running `testLoadAccountAndAddress`

in `loadPrivateKey()` in `TestEthereumKeyStorage`

`privateKey.hexData` is returning `nil`

**Comment by daihovey** [comment]
Ah.
Just read https://github.com/argentlabs/web3.swift#running-tests
Maybe best to add a comment inline in the possible failing tests so more people like me don't waste your time with issues :)

**Comment by DarthMike** [comment]
Thanks for the feedback, definitely going to improve this for next release.
