### ISSUE TITLE
Parsing error when reading ERC20 contract's `symbol` property

### ISSUE THREAD

**Issue by jtomanik** [argentlabs/web3.swift#83]
When using `public func symbol(tokenContract: EthereumAddress, completion: @escaping((Error?, String?) -> Void))` from `public class ERC20` parsing sometimes fails.

## Expected Behavior
As a consumer of this library, I should be able to retrieve ERC20 token's symbol using `public func symbol(...)` function.

## Current Behavior
Currently, call fails with `EthereumClientError.decodeIssue` for some ERC20 contracts. This is because `symbol` function call expects the result to be of `string` type as defined in ERC20 standard. However, some contracts implement `symbol` as `bytes32` type causing this failure.

## Steps to Reproduce
1. Create `let client = EthereumClient(...)` with Ropsten testnet (`https://ropsten.infura.io/`)

2. get an array of incoming ERC transfers via:
`ERC20(client: client).transferEventsTo(recipient: "0x70abd7f0c9bdc109b579180b272525880fb7e0cb")`

3. Having results like `let transfers: [ERC721Events.Transfer] = step 2 result` try to query token symbols for respective transfers using `ERC20(client: client).name(tokenContract: transfer.log.address)`. One of the contracts that are causing this issue: `"0x70503d98c63e9803233789c4ab0c33848dcca47f"`

4. Underling call `func call<T: ABIResponse>(withClient client: EthereumClient, responseType: T.Type, block: EthereumBlock = .Latest, completion: @escaping((EthereumClientError?, T?) -> Void))` will compleate yet will fail during parsing `let response = (try? T(data: res))`

**Comment by th3m477** [comment]
Thanks for identifying this.

Do you have any examples of ERC20 tokens that return bytes32 instead of string?

Please note the specification strictly defines the `symbol` property to be a string ( https://eips.ethereum.org/EIPS/eip-20 ). We stick to the defined specifications where possible, unless we see demand from popular tokens.

**Comment by brianmcmichael** [comment]
Came across this while searching for something else. If you do need an example of this, MKR token uses `bytes32` datatypes for both `name` and `symbol`.

**https://etherscan.io/token/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2**
