### ISSUE TITLE
Getting started code fails gas price call

### ISSUE THREAD

**Issue by danielnordh** [argentlabs/web3.swift#86]
Using the Getting started code for setting up the client:

```
guard let clientUrl = URL(string: "https://mainnet.infura.io/v3/<myInfuradetails>") else  { return    false}
let client = EthereumClient(url: clientUrl)
 client.eth_gasPrice(completion: { (error, currentPrice) in
    print("The current gas price is \(currentPrice)")
 })
```

Fails with the following error:

```  
Task <BEC188CB-97F7-417B-85F2-3D8A7E3781E3>.<1> finished with error [-999] 
Error Domain=NSURLErrorDomain Code=-999 "cancelled" 
UserInfo={NSErrorFailingURLStringKey=https://mainnet.infura.io/v3/<myInfuradetails>, 
NSLocalizedDescription=cancelled, 
NSErrorFailingURLKey=https://mainnet.infura.io/v3/<myInfuradetails>}

The current gas price is nil
```

I would normally guess this was an https issue but that seems unlikely here.
Any tips on how to get this library working?
(Xcode 11.3.1)

**Comment by DarthMike** [comment]
Hi @danielnordh , given the library calls `session.invalidateAndCancel()` when it's deallocated, are you keeping a strong reference to the client somewhere? Otherwise it will deallocate and cancel all tasks.

**Comment by danielnordh** [comment]
Ah, silly mistake. Yes that fixed it, thank you!

**Comment by jsdu** [comment]
I'm having issues with this myself, having the same error. @danielnordh could you provide a code sample on how you were able to solve this?
